# This plugin has been created by Bosternike (Discord: Bosternike#7428).
#
# Permission to use admin commands (/bosterparticles) - bosterparticles.commands.admin
# Permission to open GUI for another player - <gui_permission>.others (command usage /<command> [player])
# Permission to open GUI for another player:
#  Example with Particles GUI:
#    Permission: bosterparticles.particles.gui.open
#    Command: /particles [player]

# Storages:
# - YAML
# - SQLITE
# - MYSQL
Storage: YAML

MySql:
  host: 'localhost'
  port: 3306
  user: ''
  password: ''
  database: ''

Updater:
  Enabled: true
  # Delay in seconds.
  Delay: 3600

Settings:
  Prefix: '&d&lBosterParticles &8&l|'
  # Messages for player will be displayed in locale that they selected.
  # For example, if I select english, messages will be displayed from "en_EN" for me.
  # Here you can see languages and definitions: https://minecraft.fandom.com/wiki/Language
  DefaultLocale: 'en_EN'
  RunnableDelay: 0
  # User key types:
  # - UUID
  # - NAME
  userKeyType: NAME
  # Do you want player data to be loaded asynchronously?
  # Set to "false" if you want to disable this.
  LoadPlayerTrailsAsync: true
  # Log types:
  # - FINE
  # - INFO
  # - WARNING
  # - ERROR
  EnabledLoggers:
  - FINE
  - INFO
  - WARNING
  - ERROR
  # Custom trails that will be set by default.
  Defaults:
  - 'example' # This is the name of custom trail.

# You can use these trails for command (/bosterparticles set [user] [trail])
CustomTrails:
  example:
    ClearSections:
    - 'Particles'
    - 'Items'
    SetToFile:
      Items:
        1:
          ItemStack:
            material: EMERALD
            name: '&aEmerald'
            lore:
              - ''
              - '&eExample lore'
          Amount: 1
          PickupAble: false
          LifeTime: -1
      Particles:
        1:
          Type: HEART
          Amount: 1
          DustOptions: none

      