name: BosterParticles
main: net.boster.particles.main.BosterParticles
author: Bosternike
version: 1.0.3
api-version: 1.13
commands:
  bosterparticles:
    aliases: [bostertrails, particles, effects, trail, trails]